### ISSUE TITLE
Loss of data on invalid input

### ISSUE THREAD

**Issue by bugabinga** [martin-eden/lua_code_formatter#10]
Hello!

Thanks for releasing this formatter. I use it in my editor as a pretty printer on save.

I realize, that the Readme states, that this is a formatter for **valid Lua 5.3** code, but I have not found a statement what behavior is expected when receiving invalid code.

My expectation is that the formatter does nothing upon receiving garbage, but it seems to discard the invalid part and anything after that.

## Small example

```lua
--[[
Demonstrates a bug in [LCF](https://github.com/martin-eden/lua_code_formatter)
where invalid table syntax causes it to discard everything after the table.
]]

require('lcf.workshop.base')
local request = request
local get_ast = request('!.lua.code.get_ast')
local get_formatted_code = request('!.formats.lua.save')


local test_lua_code=[[
local bad_table = {  "a"    =  1,  b   =   2,  c    =   3 }
local good_table = {1,2,3,4,5}]]
local formatted =
  get_formatted_code(
    get_ast(
      test_lua_code,
      {
        indent_chunk = '  ';
        right_margin = 80;
        max_text_width = 80;
        keep_comments = true;
      }
    )
  )

local expected = [[
local bad_table = {a = 1, b = 2, c = 3}
local good_table = {1, 2, 3, 4, 5}]]

print(formatted)
print(expected)

assert(formatted == expected)
```

**Comment by martin-eden** [comment]
Thanks for example!

You are correct: formatter parses what it can until bad part. And then reformats good part.

Such behaviour came historically, I wished to reformat valid sources (WoW addons to some uniform way).

Request to keep code intact is really common. I'm going to implement this logic in next release.

My current recommendation is to use `luac -p <file_name>` to check syntax correctness.

**Comment by martin-eden** [comment]
> I realize, that the Readme states, that this is a formatter for valid Lua 5.3 code, but I have not found a statement what behavior is expected when receiving invalid code.

In case with invalid code both outcomes possible: it may or may not preserve source tokens.

Lua grammar used in parser currently allows some incorrect code like `f() = a` or `a, b`. I'm going to fix this but the price will be about 10% longer parsing stage.

**Comment by bugabinga** [comment]
Von meinem iPhone gesendet

> Am 21.01.2018 um 21:45 schrieb martin-eden <notifications@github.com>:
> 
> Thanks for example!
> 
> You are correct: formatter parses what it can until bad part. And then reformats good part.
> 
> Such behaviour came historically, I wished to reformat valid sources (WoW addons to some uniform way).
> 
> Request to keep code intact is really common. I'm going to implement this logic in next release.
> 
> My current recommendation is to use luac -p <file_name> to check syntax correctness.
> 
Since I use luacheck in my editor anyways, I configured the formatter to only run if luacheck returns no error. I imagine it does something similar to 

    luac -p ...

internally. 


Thanks for taking the time to address this!

**Comment by martin-eden** [comment]
@bugabinga In recent version I've added option to keep unparsed tail (ON by default).

lcf still gives no guarantees for invalid input but behaves better in that case.

**Comment by bugabinga** [comment]
> lcf still gives no guarantees for invalid input but behaves better in that case
> 
It is very much appreciated nonetheless.
