### ISSUE TITLE
Syntax-valid Lua code deleted upon formatting

### ISSUE THREAD

**Issue by vadi2** [martin-eden/lua_code_formatter#13]
Using the dfa81b95b0955a893e52400c50b1b78861165001 commit (5.1 before the latest update) will delete most of the code save for one function if the formatter is used on it: https://hastebin.com/aqokatihog.lua

The code is syntax-valid Lua however, so this is really strange and unexpected.

Can't test latest update atm, 5.1 branch [doesn't load](https://github.com/martin-eden/lua_code_formatter/issues/12).

**Comment by martin-eden** [comment]
Confirmed. Investigating this.

**Comment by martin-eden** [comment]
`goto` is reserved word since Lua 5.2. As this parser is supposed to format Lua 5.3 code it's ok that it fails on 5.1 code that uses `goto` as variable.
```lua
function mmp.gotoArea (where, number, dashtype, exact)
  local goto = maptable[where]
  if goto then
    mmp.gotoRoom(goto, dashtype)
    return
  end
end
```
```
luac: all_bugs.lua:2: <name> expected near 'goto'
```

All branches and versions of formatter will fail to parse this code. But in recent versions I've added option to keep unparsed tail (ON by default) so unparsed part is kept.

**Comment by vadi2** [comment]
I'm using the 5.1 branch on 5.1 valid code. Is the fix for this to use the keep unparsed code option?

**Comment by martin-eden** [comment]
Current code from 5.1 branch keeps unparsed tail by default. Problem was in wrong example code, I've just answered at that issue.

(Branch `5.1` assumes that code formatter for Lua 5.3 code is implemented on Lua 5.1.)

**Comment by vadi2** [comment]
It's not making sense to me, sorry. It's perfectly valid Lua code per 5.1 interpreter:

```lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> mmp = {}
> function mmp.gotoArea (where, number, dashtype, exact)
>>   local goto = maptable[where]
>>   if goto then
>>     mmp.gotoRoom(goto, dashtype)
>>     return
>>   end
>> end
> 
```

Given the formatters corruption of invalid code, I already check that it's valid with Lua before handing it off to the formatter. What should I do now when the formatter thinks the valid code isn't anymore and deletes it?

**Comment by martin-eden** [comment]
This formatter is for Lua 5.3 code. Using `goto` as name is illegal in 5.3 (but legal in 5.1). Formatter keeps unrecognized code by default.

As a workaround to format 5.1 code you can remove `goto` from list of reserved words [here](https://github.com/martin-eden/lua_code_formatter/blob/e88620947e7cd59b01527b0967342ea65076a844/workshop/formats/lua/keywords.lua#L16). And remove label- and goto- constructions from syntax [here](https://github.com/martin-eden/lua_code_formatter/blob/e88620947e7cd59b01527b0967342ea65076a844/workshop/formats/lua/syntax/statements.lua#L58).

**Comment by vadi2** [comment]
Ah ok. What do you think about the 5.1 branch being compatible with 5.1 code by default?

**Comment by martin-eden** [comment]
I think this is what many people wish. But not going to do it personally. I'll be glad to consult if someone is going to create fork for Lua 5.1 syntax.
