### ISSUE TITLE
Accept valid lua 5.1 code

### ISSUE THREAD

**Issue by keneanung** [martin-eden/lua_code_formatter#14]
This is more or less a result of #13: I modified the `5.1` branch in such a way that it should format valid lua 5.1 code, namely to allow the variable name `goto` and remove some binary operators, though those should not break the formatter.

However, i am unsure whether the changes are welcome in the main repository and how you want to include them. I created a new branch from the common ancestor of the code we use and this repository, so it should be easy to include in some way.

You can find the branch at https://github.com/keneanung/lua_code_formatter/tree/code_5.1-syntax_5.1

**Comment by martin-eden** [comment]
Thank you for implementing that changes! 

I'm ready to include them as separate branch in my repository. It would be more easy if you create push request with new branch. (As I don't know how to import commit with preserving authorship.)

**Comment by keneanung** [comment]
I can do that, but you'll need to create a new Branch first, if you don't want these changes in an existing branch (I assume you want the 5.1 branch to still format 5.3 syntax?)

**Comment by martin-eden** [comment]
I've just created branch `5.1-syntax_5.1` for this.

**Comment by martin-eden** [comment]
Accepted.
