### ISSUE TITLE
Commit disappeared

### ISSUE THREAD

**Issue by keneanung** [martin-eden/lua_code_formatter#17]
Our project used the tip of the `5.1-syntax_5.1` branch as submodule which used to be commit e152adaf15416821d08a534d975bcd2664ce8b6d. However, this commit seems to have disappeared (a force push?) and our builds are breaking now.

Could you restore that commit?

**Comment by martin-eden** [comment]
My bad. Restored that commit.

Thank you!

**Comment by keneanung** [comment]
Our builds work again, thanks for the quick reaction.
