### ISSUE TITLE
Incorporate into Textadept?

### ISSUE THREAD

**Issue by ryanpcmcquen** [martin-eden/lua_code_formatter#18]
I'd like to roll this awesome formatter into Textadept. Is there a way to get all of the functionality in one file? I've been looking through the code and I'm not sure where everything is yet.

**Comment by martin-eden** [comment]
Well, no. My development model based on tiny one-screen files. You can try [Squish](https://github.com/LuaDist/squish). Maybe it can pack those files in one.

Can you describe problem with Textadept? It lacks "require"? For example, World of Warcraft Lua subsystem lacks "require" too. But you can list required modules in accompanying XML file.


Regarding code. After installation via LuaRocks, home directory of files hive have alias "lcf". So `require('lcf.workshop.base')` in `lua_reformat.lua` loads `workshop/base.lua`.

This module exports core function `request`. Which is `require` wrapped such way that it allows relative pathes to module. (Unless path is started with `!`. Which is absolute path this way.)

**Comment by ryanpcmcquen** [comment]
Squish looks like a great tool, I will give it a spin. Textadept does support `require`, but I was hoping to roll the beautifier into my config for portability's sake. Where does the reformat logic live?

**Comment by martin-eden** [comment]
Formatting handlers live in https://github.com/martin-eden/lua_code_formatter/tree/master/workshop/formats/lua/formatter/handlers . They process nodes of modified parse tree and do output to "printer" - some abstraction of typewriter.

**Comment by martin-eden** [comment]
As formatter installed as command-line tool (via LuaRocks), you may just call it externally with `os.execute()` from your script in Textadept.
