### ISSUE TITLE
Unexpect formatting result

### ISSUE THREAD

**Issue by vingi** [martin-eden/lua_code_formatter#19]
the format functionality might mess up code comments when I use format functionality in right-click in code editor,  especially when code comments are in the middle line with two the real code lines, formattor seems to shuffle all the code comments up to the top..

before formatting below:
![unknown (2)](https://user-images.githubusercontent.com/1768640/62794108-d7b98100-bb05-11e9-9fdb-bbc6f48adffb.png)

after formatting below:
![unknown (3)](https://user-images.githubusercontent.com/1768640/62794115-dd16cb80-bb05-11e9-96fd-6ad3b29dc69e.png)

**Comment by Kebap** [comment]
Smaller example confirmed like this:
Before: 
![before](https://cdn.discordapp.com/attachments/283582439002210305/609446673466392578/unknown.png)
After: 
![after](https://cdn.discordapp.com/attachments/283582439002210305/609446737115086858/unknown.png)
Is there any way to prevent this from being destroyed?

**Comment by martin-eden** [comment]
Hi guys, sorry for late response, just returned from vacation.

This is "documented flaw" in readme.md: "Comments are "sinked-up" to statements level.". 

I will add more sophisticated comments handling in next versions.
