### ISSUE TITLE
Hi~

### ISSUE THREAD

**Issue by Alloyed** [martin-eden/lua_code_formatter#2]
Hi, I was shopping around for code formatters in lua and saw yours on the mailing list. I'd like to support it as an optional backend for my [LSP server](http://langserver.org), but I have a few questions that your readme didn't resolve:
* Does the implementation only run on 5.3, or does it only implement formatting for 5.3 source code? Both?
* looking at the API example, it seems like "lcf.workshop.base" installs global variables. is this correct?
* How would a user of the CLI interface pass in formatting parameters? Is there a project specific file, like `.luacheckrc` for luacheck?
* How would I implement "range" formatting, where only a subset of a larger file is formatted? Presumably the formatting of this block would change depending on its context.
* How does it compare in terms of output to the other formatters listed at Alloyed/lua-lsp#2?

Thanks in advance~

**Comment by martin-eden** [comment]
Hi!

* Formatter implemented on Lua 5.3. It supports Lua 5.3 syntax (that new binary operators). It will very likely reformat code for Lua 5.1.

    In principle it is possible to backport code to Lua 5.1. I may done it in a day but do not see really good reason to use old Lua version.

* Yes, `workshop.base` installs global variables. Most usable of them is `request()` -- `require()` with relative paths. All my code is binded with this function.

* There are no way to pass formatting parameters via command-line yet. Advanced usage assumed to be via language calls.

    However you can change default formatting options by editing `pretty_lua_options` table values in file `/usr/local/share/lua/5.3/lcf/reformat.lua`.

* Ugh, hard question. You can pass any string with chunk of lua code to function in `workshop.lua.code.get_ast`. It will parse to the first syntax error and return parsed tree which may be used further.

    Say you have code like

    ```
    if cond then
      --[1]
      many()
      statements()
      here()
    end
    ```

    You may pass lines after "--[1]":

    ```
      many()
      statements()
      here()
    end
    ```

    Which will be parsed to three function calls. However when you call function from `workshop.formats.lua.save` for them, it returns

    ```
    many()
    statements()
    here()
    ```
    -- indent is gone.

    You may try to avoid this by applying indent manually after formatting and setting smaller right margin. But I think the right thing is to add some parameter like `.initial_indent` for `workshop.formats.lua.save`. If this really needed this may be done.

* Somewhere in past I tried https://github.com/stravant/LuaMinify/blob/master/FormatBeautiful.lua. Several years later I've done my own formatter and didn't do any comparisions. So can't compare it with others.

    This formatter can process lua files several megabytes size. Sample speed is 57KiB/s for 694KiB test file.

    Also as it completely parses lua file, no original whitespaces between tokens survive. (I've seen that some formatters reformat code only partially.)

    Third, it tries to be smart. It has several representation variants for syntax entities and applies them, trying to get smallest number of lines under fixed right margin:

    ```
    local function f(a, b, c, ...)
    end

    local function _____________________________________________________f(
      a,
      b,
      c,
      ...
    )
    end
    ```

    These iterations add execution time for complex cases.

* Besides all, formatter is just illustration of lua code parser. 

    With parser you can catch references to global variables, implement nice code metrics as "statements per file" (instead "lines of code"), automatically place ldoc comments before function definition and many other sexy things.

**Comment by mpeterv** [comment]
Old Lua versions are still used, in particular LuaJIT which is somewhere between Lua 5.1 and 5.2.

Speaking of LuaJIT, it appears that LuaJIT cdata literals like `1LL` are not supported properly.

Getting rid of globals is simple, just import all the globals into locals explicitly. This includes adding something like `local request = require('workshop.base.request` to each file with dependencies.

**Comment by martin-eden** [comment]
* I do not feel need for performance at this stage. Proven solutions should be recoded in normal compiled language, not LuaJIT surrogate. Although I'll add backport for Lua 5.1 someday because it is not really hard.

* Lua dialects are not supported. I have no syntax descriptions for them to implement by paper and do not use them to implement by experimenting. 

    (But it's quite easy to extend number syntax (if `1LL` means int64 number) by modifying `workshop.formats.lua.load.syntax.type_number`. (Some experience from puzzle games would be useful.))

* Yes, I know how to get rid of globals. But feel perfectly OK with my functions that intentionally exported to global table. User can always wrap code to `pcall()` if he do not trust/like it.

**Comment by martin-eden** [comment]
BTW I've added command-line support in current version.

**Comment by vadi2** [comment]
What is the latest on range indenting? Given that the formatter is naturally opinionated, there would be cases where hand-formatting part of a file is preferred.

**Comment by martin-eden** [comment]
Probably best way to keep part of original code is to hack comment definition. Treat `--c( ... )c` or something like long comment. (Gave more extended answer in that issue.)
