### ISSUE TITLE
Rundundent files left behind by modifications to support Lua 5.1

### ISSUE THREAD

**Issue by SlySven** [martin-eden/lua_code_formatter#20]
It seems that #15 left behind two unneeded files in the `5.1-syntax_5.1` branch that we use (now, we had forgotten to switch over when that and #16 were done!) in Mudlet:
* `workshop/formats/lua/formatter/handlers/statements/goto_statement.lua`
* `workshop/formats/lua/formatter/handlers/statements/label_statement.lua`

these are not relevant for 5.1 as, of course that version does not support the `goto` functionality regarded as leading to 🍝 code in other coding languages that was adopted in a later Lua version!

**Comment by martin-eden** [comment]
I don't see these files in `5.1-syntax_5.1` branch. 

Formatter originally targeted Lua 5.3 version of language and was written in Lua 5.3. Later there was request to make it runnable in Lua 5.1. So branch `5.1` was created. And later there was request to adopt it to Lua 5.1 syntax. That's what @keneanung did in [this commit](https://github.com/martin-eden/lua_code_formatter/commit/dbdddb189429b484cdc707a11cfc6b026894e1bc) and branch `5.1-syntax_5.1` was created. 

Sorry for non-clear branch names, I've not expected that requests at creation time.
