### ISSUE TITLE
Commas get changed to semicolons if max_text_width is small enough

### ISSUE THREAD

**Issue by vadi2** [martin-eden/lua_code_formatter#3]
Given the following input:

```lua
local picturelabel = Geyser.Label:new({
  name = "picturelabel",
  x = "50%", y = "90%",
  width = "97px", height = "46px",
})
```

The script outputs the following for max width 65:
```lua
local picturelabel =
  Geyser.Label:new(
    {
      name = "picturelabel";
      x = "50%";
      y = "90%";
      width = "97px";
      height = "46px";
    }
  )
```

Notice how semicolons are now used for the table output. Changing max width to 120 gives gives commas as expected:

```lua
local picturelabelclose =
  Geyser.Label:new(
    {name = "picturelabelclose", x = "-20px", y = "5px", width = "15px", height = "15px"},
    picturelabel
  )
```

**Comment by martin-eden** [comment]
Indeed this is intended feature.

Under the hood formatter usually tries several variants to represent element to fit it under given margin. In case of table value two styles implemented: 

one-line: `{a, b, c = c}`

multi-line: 
```
{
  a;
  b;
  c = c;
}
```
Corresponding code in https://github.com/martin-eden/lua_code_formatter/blob/master/workshop/formats/lua/save/formatter/handlers/expressions/data_types/table.lua#L1

So you may change behavior to your needs.

**Comment by vadi2** [comment]
Got it, thanks.

**Comment by vadi2** [comment]
Do you think this could be an option? It would save us from maintaining a fork.

**Comment by vadi2** [comment]
`;` in tables is just not very Lua-like.

**Comment by martin-eden** [comment]
I'm not going to make such command-line option. Else there still too many similar options to add.

I consider representation routines as customizable options. So the "right" way is to change mentioned [code](https://github.com/martin-eden/lua_code_formatter/blob/master/workshop/formats/lua/save/formatter/handlers/expressions/data_types/table.lua#L1).

For me, it's perfectly OK when someone wants to implement their own formatting style. This was one of reasons why I wrote this formatter. So make your fork if you wish. Current formatting style is just my personally biased vision.

**Comment by vadi2** [comment]
That's a pity, because forking means additional workload in keeping the changed synced. Yes, formatting styles should be different, but you don't see people forking `clang-format` just to use their own...

**Comment by martin-eden** [comment]
I've thought about it.

User who wish to configure code formatter to his own style
need tools for this. This may be command-line parameters or
files with formatting templates. Maybe like

```lua
local_function = [[

local function $name($args)
  $body
end
]]
```

This is easy to understand and use but requires to implement some
inner language to process templates. And this language tends to be
too limited (but simple) or too obscure.

Extreme solution is to throw away any configs. Hardcode all behavior.
Luckily this is viable solution for elegant dynamic languages like Lua.

So to format local function definition, code calls some routine which
should add some text to object "printer".

```lua
handlers = {
  local_function = function(self, node)
    self.printer:add_empty_line()
    self.printer:add('local function ')
    process(node.name)
    self.printer:add('(')
    process(node.args)
    self.printer:add(')')
    -- ... and so on
  end,
}
```

This approach is harder to understand and read. But still easy to use
and a lot more powerful. For example, you may print SHA-1 hash instead
of names. Or try several alternative chunk representations.

**Comment by vadi2** [comment]
Yeah, I like the second approach!

**Comment by martin-eden** [comment]
@vadi2 In recent version I've made comma as the only delimiter for tables.

**Comment by vadi2** [comment]
Sweet! Thanks!
