### ISSUE TITLE
Is it possible to keep shorthand syntax?

### ISSUE THREAD

**Issue by vadi2** [martin-eden/lua_code_formatter#4]
```lua
do for k,v in pairs{} do print(k,v) end end
```
Gets converted to:

```lua
do
  for k, v in pairs({}) do
    print(k, v)
  end
end
```

Where the shorthand syntax for calling functions with a single table argument is lost. Is it possible to keep it?

**Comment by martin-eden** [comment]
No. Both `pairs{}` and `pairs({})` is converted to same structure - function call with single table argument.

On the other hand, by extending representator's code **all** function calls with single argument which is table or string may be represented without parenthesis. (Just checked it.)

**Comment by vadi2** [comment]
OK
