### ISSUE TITLE
How to implement range-based formatting?

### ISSUE THREAD

**Issue by vadi2** [martin-eden/lua_code_formatter#5]
As range-based formatting isn't supported out of the box https://github.com/martin-eden/lua_code_formatter/issues/2#issuecomment-332376877, what would be the recommended way of implementing it?

The difficulty I see is how to figure out what the initial indent should be - can the AST help here at all?

**Comment by martin-eden** [comment]
(This is open-ended question, I don't know best answer.)

Yes, the problem will be how to keep original formatting.

My idea is to masquerade constant code as comment records. This may be done at parsing stage by extending [comment](https://github.com/martin-eden/lua_code_formatter/blob/master/workshop/formats/lua/load/syntax/words/comment.lua) syntax.

(You can see both original and transformed ASTs by typing `lua.get_ast <f_in>` and `lua.get_formatter_ast <f_in>` correspondingly.)    

Another option is to strip constant code from source before passing source to formatter. And then insert it back. This approach is more simple to implement and more limited.

**Comment by vadi2** [comment]
Exploring option 2, how can I find out what level of indenting should the code get?

For example if I have the following:

```lua
if true then
// keep formatting in this block
functioncall()
else
// format this block
if true then
functioncall() functioncall() functioncall()
end
end
```

The `// format this block` needs to be indented by two spaces because it's on the first level down, but how can I find out that it's on the first level down?

**Comment by martin-eden** [comment]
Internally there is no indent conception.

(Transformed AST is represented as indented text but there is no
back link from text to structure. It may be represented as sounds or
bytecode.)

So we need some hack. Lets add `// <UID>` before `// format this block`,
then format all code, then search line with \<UID\> to get indent.

**Comment by vadi2** [comment]
I'll try that out. The 5.1 code formatter was deployed to production yesterday by the way, people are pretty happy to see such a feature: https://www.mudlet.org/2017/12/mudlet-3-6-0-code-beautifier-search-online-prompt-trigger-type-more-ui-customisation

Initial feedback is good, people would like customisation options though.

**Comment by martin-eden** [comment]
Wow! Glad to see it in use as part of bigger project!

**Comment by martin-eden** [comment]
I've created [issue](https://github.com/martin-eden/lua_code_formatter/issues/9) for discussion possible customisation options.

Closing current issue. Interactive and selection-based mode was not intended initially. (But I'm thinking about ways to support them.)
