### ISSUE TITLE
How to keep blank lines?

### ISSUE THREAD

**Issue by vadi2** [martin-eden/lua_code_formatter#6]
```
> lua_code_str = [[echo("hello")
>> 
>> 
>> echo("bye")
>> 
>> cecho("no")]]
>   return get_formatted_code(get_ast(lua_code_str))
echo("hello")
echo("bye")
cecho("no")
> 
```

How can I keep the blank lines? They are important to have for formatting reasons, some people use them to space elements out.

**Comment by martin-eden** [comment]
Alas, this is not possible in current implementation.

Nicely written code lose from auto-reformatting. Intention was to made trash code written by Lua novices readable. Not just change indentation in good code.
